on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Stale branch management
    steps:
      - name: Clean up stale branches
        id: clean_stale_branhces
        uses: etiennemartin/stale-branch-action@v0.1
        with:
          expiry: 0 # Days
          grace: 0 # days
          merge_target: "master" # Target branch
          pr_title: "This is a custom title!"
          pr_message: "This is a customer Message yo!"
