on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Clean up stale branches
        id: clean_stale_branhces
        uses: etiennemartin/stale-branch-action@v0.1
        with:
          expiry: 365 # Days
          grace: 14 # days
